### ISSUE TITLE
Code licensing ?

### ISSUE THREAD

**Issue by AkechiShiro** [0xfalafel/hextazy#1]
Hello could you add a license to the code please ?

It's just to package this software into [`Nixpkgs`](https://github.com/nixos/nixpkgs), usually we need to set the license in the metadata of the package.

**Comment by AkechiShiro** [comment]
@Faelian any news ?

**Comment by 0xfalafel** [comment]
Hey, thanks a lot for packaging it. I have just added an **MIT License** file.
Please let me know if you have any other issues.
