### ISSUE TITLE
Delete byte using delete key

### ISSUE THREAD

**Issue by HanzCEO** [0xfalafel/hextazy#4]
I have been scouring the internet for a simple TUI hex-editor who can delete a single byte

**Comment by 0xfalafel** [comment]
You can with the release `0.7`, but I haven't document things in the README yet.

Here is how to do it:

* `hextazy yourfile.bin`
* __Switch to insert mode__ with `Ctrl + J`
* go to the byte you want to delete. You can use `:0xaddr` where addr is the address of the byte in hexadecimal.
* __press the delete key__ `Del` to remove the byte

**Comment by HanzCEO** [comment]
Thank you very much, it works really well!

**Comment by 0xfalafel** [comment]
I have updated the `README` with the new features. Glad it could be of use ;)
